////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define the messenger
// commands for the XeNeuDT project.
// All geometry, physics, io managements, etc, happen here
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

//
//	GEANT4 includes
//
#include "G4UIdirectory.hh"
// uncomment the headers that you will need
//#include "G4UIcmdWithAnInteger.hh"
//#include "G4UIcmdWithoutParameter.hh"
//#include "G4UIcmdWithAString.hh"
//#include "G4UIcmdWithABool.hh"
//#include "G4UIcmdWith3VectorAndUnit.hh"
//#include "G4UIcmdWithADoubleAndUnit.hh"
//#include "G4UIcmdWith3Vector.hh"
//#include "G4UIcmdWithADouble.hh"
#include "globals.hh"

//
// Project-specific includes
//
#include "XeNeuDTMessenger.hh"
#include "XeNeuDTDetector.hh"

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					Messenger()
//------++++++------++++++------++++++------++++++------++++++------++++++------
XeNeuDTMessenger::XeNeuDTMessenger( XeNeuDTDetector *Det )
  : XeNeuDTdetector( Det )
{
  //  Set up the directory
  XeNeuDTDir = new G4UIdirectory( "/XeNeuDT/" );
  XeNeuDTDir->SetGuidance( "All XeNeuDT project commands are contained under /XeNeuDT/" );

}

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					~Messenger()
//------++++++------++++++------++++++------++++++------++++++------++++++------
XeNeuDTMessenger::~XeNeuDTMessenger()
{
  //delete everything that you declared with new
  delete XeNeuDTDir;

}

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					SetNewValue()
//------++++++------++++++------++++++------++++++------++++++------++++++------
void XeNeuDTMessenger::SetNewValue( G4UIcommand *command, G4String newValue )
{
  
}

