####################################################################################################
# example macro for the LUXSim package                                                             #
#                                                                                                  #
# Change log:                                                                                      #
# 19 Aug 2013 - Initial submission (Vic)                                                           #
#                                                                                                  #
####################################################################################################
/run/verbose 1
/control/verbose 0
/tracking/verbose 0
/grdm/verbose 0
/process/verbose 0

# Set up visualization - Comment this stuff out if you want to skip visualization
#/vis/open OGLSQt 1200x1200-0+0
#/vis/open VRML2FILE
#/vis/drawVolume
#/vis/scene/add/trajectories
#/vis/scene/endOfEventAction accumulate
#/tracking/storeTrajectory 1
#/vis/viewer/set/viewpointVector 0.5 0.75 1
#/vis/viewer/set/upVector 0 0 1
#/vis/viewer/zoom 0 
#/vis/viewer/set/viewpointThetaPhi 45 45             
#/vis/viewer/set/style surface

# Set up visualization so that we don't cloud the issue with neutrinos - Comment this stuff out if you want to skip visualization
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add nu_e
#/vis/filtering/trajectories/particleFilter-0/add nu_mu
#/vis/filtering/trajectories/particleFilter-0/add nu_tau
#/vis/filtering/trajectories/particleFilter-0/add anti_nu_e
#/vis/filtering/trajectories/particleFilter-0/add anti_nu_mu
#/vis/filtering/trajectories/particleFilter-0/add anti_nu_tau
#/vis/filtering/trajectories/particleFilter-0/invert true

# Color keys: white, gray, grey, black, red, green, blue, cyan, magenta, yellow - Comment this stuff out if you want to skip visualization
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
#/vis/modeling/trajectories/drawByParticleID-0/set e- magenta
#/vis/modeling/trajectories/drawByParticleID-0/set proton cyan
#/vis/modeling/trajectories/drawByParticleID-0/set neutron grey
#/vis/modeling/trajectories/drawByParticleID-0/set gamma green
#/vis/modeling/trajectories/drawByParticleID-0/set opticalPhoton yellow

# This next set of lines is to, as it appears, initialize the simulation
/run/initialize

# Set the output directory
#/Bacc/io/outputDir /usr/workspace/wsb/lenardo1/simulations/TMS_ScherzingerAmBeSpecNeutrons_Conical_CylindricalSource/
/Bacc/io/outputDir ./
/Bacc/io/outputName Xe127Radioassay_Xe127SourceInCylinder
/Bacc/io/updateFrequency 100000


# Set the random seed
#/Bacc/randomSeed 0

# Select the kind of detector to use
#/Bacc/detector/select simpleExample
#/Bacc/detector/select complexExample
#/Bacc/detector/select LLNLSinglePhase
/Bacc/detector/select Xe127RadioassayDetector
#/XeNeu/ddShieldingOn true

# Update geometry
/Bacc/detector/update

# Set the record level for one of the volumes to write some information about it
#/Bacc/detector/recordLevel LiquidXeTarget 2 # For "simpleExample" or "complexExample"
#/Bacc/detector/recordLevel activeVolume 2 # For "LLNLSinglePhase"
/Bacc/detector/recordLevel ge_detector_crystal 2 # For "GNARRLIDetector"



#/gps/particle e-
#/gps/energy 1 MeV
#/gps/ene/type Gauss
#/gps/ene/sigma 1.22 MeV

/gps/particle ion 
/gps/energy 0 keV 
/gps/ion 54 127 
/grdm/nucleusLimits 127 127 54 54

/gps/position 10.16 0 2.54 cm
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/radius 2.31 cm
/gps/pos/halfz 5.08 cm
/gps/pos/rot1 1 0 0
/gps/pos/rot2 0 0 -1
/gps/ang/type iso
#/gps/hist/type theta
#/gps/ang/mintheta 0. deg
#/gps/ang/maxtheta 15. deg
#/gps/ang/minphi 160. deg
#/gps/ang/maxphi 200. deg
#/gps/ang/rot1 0 0 -1
#/gps/ang/rot2 0 -1 0


/Bacc/physicsList/useOpticalProcesses 0

/Bacc/beamOn 5000000

exit
