////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define the messenger
// commands for the TestShield project.
// All geometry, physics, io managements, etc, happen here
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

//
//	GEANT4 includes
//
#include "G4UIdirectory.hh"
// uncomment the headers that you will need
//#include "G4UIcmdWithAnInteger.hh"
//#include "G4UIcmdWithoutParameter.hh"
//#include "G4UIcmdWithAString.hh"
//#include "G4UIcmdWithABool.hh"
//#include "G4UIcmdWith3VectorAndUnit.hh"
#include "G4UIcmdWithADoubleAndUnit.hh"
//#include "G4UIcmdWith3Vector.hh"
//#include "G4UIcmdWithADouble.hh"
#include "globals.hh"

//
// Project-specific includes
//
#include "TestShieldMessenger.hh"
#include "TestShieldDetector.hh"

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					Messenger()
//------++++++------++++++------++++++------++++++------++++++------++++++------
TestShieldMessenger::TestShieldMessenger( TestShieldDetector *Det )
  : TestShielddetector( Det )
{
  //  Set up the directory
  TestShieldDir = new G4UIdirectory( "/TestShield/" );
  TestShieldDir->SetGuidance( "All TestShield project commands are contained under /TestShield/" );
  
  ShieldingRadiusCommand = new G4UIcmdWithADoubleAndUnit( "/TestShield/shieldingRadius", this );
  ShieldingRadiusCommand->AvailableForStates( G4State_PreInit, G4State_Idle );

}

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					~Messenger()
//------++++++------++++++------++++++------++++++------++++++------++++++------
TestShieldMessenger::~TestShieldMessenger()
{
  //delete everything that you declared with new
  delete ShieldingRadiusCommand;
  delete TestShieldDir;

}

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					SetNewValue()
//------++++++------++++++------++++++------++++++------++++++------++++++------
void TestShieldMessenger::SetNewValue( G4UIcommand *command, G4String newValue )
{
  if( command == ShieldingRadiusCommand ) 
      TestShielddetector->SetShieldingRadius( G4UIcmdWithADoubleAndUnit::GetNewDoubleValue( newValue.data() )  );
}

