################################################################################
# GNUmakefile for the generator subsystem
#
# Change log:
# 18 March 2009 - Initial submission (Kareem)
#
################################################################################

name := generator

include ../BaccConfig/Libraries.gmk
