////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define the messenger
// commands for the AmBeXe127Source project.
// All geometry, physics, io managements, etc, happen here
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

//
//	GEANT4 includes
//
#include "G4UIdirectory.hh"
// uncomment the headers that you will need
//#include "G4UIcmdWithAnInteger.hh"
//#include "G4UIcmdWithoutParameter.hh"
//#include "G4UIcmdWithAString.hh"
//#include "G4UIcmdWithABool.hh"
//#include "G4UIcmdWith3VectorAndUnit.hh"
//#include "G4UIcmdWithADoubleAndUnit.hh"
//#include "G4UIcmdWith3Vector.hh"
//#include "G4UIcmdWithADouble.hh"
#include "globals.hh"

//
// Project-specific includes
//
#include "AmBeXe127SourceMessenger.hh"
#include "AmBeXe127SourceDetector.hh"

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					Messenger()
//------++++++------++++++------++++++------++++++------++++++------++++++------
AmBeXe127SourceMessenger::AmBeXe127SourceMessenger( AmBeXe127SourceDetector *Det )
  : AmBeXe127Sourcedetector( Det )
{
  //  Set up the directory
  AmBeXe127SourceDir = new G4UIdirectory( "/AmBeXe127Source/" );
  AmBeXe127SourceDir->SetGuidance( "All AmBeXe127Source project commands are contained under /AmBeXe127Source/" );

}

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					~Messenger()
//------++++++------++++++------++++++------++++++------++++++------++++++------
AmBeXe127SourceMessenger::~AmBeXe127SourceMessenger()
{
  //delete everything that you declared with new
  delete AmBeXe127SourceDir;

}

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					SetNewValue()
//------++++++------++++++------++++++------++++++------++++++------++++++------
void AmBeXe127SourceMessenger::SetNewValue( G4UIcommand *command, G4String newValue )
{
  
}

