////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define the messenger
// commands for the DuMmYkEy project.
// All geometry, physics, io managements, etc, happen here
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

//
//	GEANT4 includes
//
#include "G4UIdirectory.hh"
// uncomment the headers that you will need
//#include "G4UIcmdWithAnInteger.hh"
//#include "G4UIcmdWithoutParameter.hh"
//#include "G4UIcmdWithAString.hh"
//#include "G4UIcmdWithABool.hh"
//#include "G4UIcmdWith3VectorAndUnit.hh"
//#include "G4UIcmdWithADoubleAndUnit.hh"
//#include "G4UIcmdWith3Vector.hh"
//#include "G4UIcmdWithADouble.hh"
#include "globals.hh"

//
// Project-specific includes
//
#include "DuMmYkEyMessenger.hh"
#include "DuMmYkEyDetector.hh"

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					Messenger()
//------++++++------++++++------++++++------++++++------++++++------++++++------
DuMmYkEyMessenger::DuMmYkEyMessenger( DuMmYkEyDetector *Det )
  : DuMmYkEydetector( Det )
{
  //  Set up the directory
  DuMmYkEyDir = new G4UIdirectory( "/DuMmYkEy/" );
  DuMmYkEyDir->SetGuidance( "All DuMmYkEy project commands are contained under /DuMmYkEy/" );

}

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					~Messenger()
//------++++++------++++++------++++++------++++++------++++++------++++++------
DuMmYkEyMessenger::~DuMmYkEyMessenger()
{
  //delete everything that you declared with new
  delete DuMmYkEyDir;

}

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					SetNewValue()
//------++++++------++++++------++++++------++++++------++++++------++++++------
void DuMmYkEyMessenger::SetNewValue( G4UIcommand *command, G4String newValue )
{
  
}

