////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define the messenger
// commands for the NeutronAttenuationTest project.
// All geometry, physics, io managements, etc, happen here
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

//
//	GEANT4 includes
//
#include "G4UIdirectory.hh"
// uncomment the headers that you will need
//#include "G4UIcmdWithAnInteger.hh"
//#include "G4UIcmdWithoutParameter.hh"
//#include "G4UIcmdWithAString.hh"
//#include "G4UIcmdWithABool.hh"
//#include "G4UIcmdWith3VectorAndUnit.hh"
#include "G4UIcmdWithADoubleAndUnit.hh"
//#include "G4UIcmdWith3Vector.hh"
//#include "G4UIcmdWithADouble.hh"
#include "globals.hh"

//
// Project-specific includes
//
#include "NeutronAttenuationTestMessenger.hh"
#include "NeutronAttenuationTestDetector.hh"

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					Messenger()
//------++++++------++++++------++++++------++++++------++++++------++++++------
NeutronAttenuationTestMessenger::NeutronAttenuationTestMessenger( NeutronAttenuationTestDetector *Det )
  : NeutronAttenuationTestdetector( Det )
{
  //  Set up the directory
  NeutronAttenuationTestDir = new G4UIdirectory( "/NeutronAttenuationTest/" );
  NeutronAttenuationTestDir->SetGuidance( "All NeutronAttenuationTest project commands are contained under /NeutronAttenuationTest/" );
  
  ShieldingThicknessCommand = new G4UIcmdWithADoubleAndUnit( "/NeutronAttenuationTest/shieldingThickness", this );
  ShieldingThicknessCommand->AvailableForStates( G4State_PreInit, G4State_Idle );

}

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					~Messenger()
//------++++++------++++++------++++++------++++++------++++++------++++++------
NeutronAttenuationTestMessenger::~NeutronAttenuationTestMessenger()
{
  //delete everything that you declared with new
  delete ShieldingThicknessCommand;
  delete NeutronAttenuationTestDir;

}

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					SetNewValue()
//------++++++------++++++------++++++------++++++------++++++------++++++------
void NeutronAttenuationTestMessenger::SetNewValue( G4UIcommand *command, G4String newValue )
{
  if( command == ShieldingThicknessCommand ) 
      NeutronAttenuationTestdetector->SetShieldingThickness( G4UIcmdWithADoubleAndUnit::GetNewDoubleValue( newValue.data() )  );
}

