////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define GammaCounter geometry
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

#ifndef GammaCounterDetector_HH
#define GammaCounterDetector_HH 1

//
//      GEANT4 includes
//
#include "globals.hh"

//
//      BACCARAT includes
//
#include "BaccDetector.hh"
#include "BaccManager.hh"

//
//	Project-specific includes
//

//
//      Class forwarding
//
class G4LogicalVolume;
class BaccDetectorComponent;
class G4NistManager;
class BaccMaterials;
class GammaCounterMessenger;
class GammaCounterMaterials;
class TestShieldMaterials;

//------++++++------++++++------++++++------++++++------++++++------++++++------
class GammaCounterDetector : public BaccDetector
{
public:
  GammaCounterDetector( G4String, G4String );
  ~GammaCounterDetector();
  
  void BuildDetector();
  G4ThreeVector SetOrigin(BaccDetectorComponent *);
  void InitializeDetector();

  //  Registration methods below
  void SetShieldingRadius( G4double val ) { shieldingRadius = val; }
  
private:
  GammaCounterMessenger *GammaCountermessenger;
  GammaCounterMaterials *GammaCountermaterials;
  G4NistManager *NISTmaterials;
  BaccMaterials *BACCmaterials;
  TestShieldMaterials * TestShieldmaterials; 

  G4double shieldingRadius;
  
};

#endif
