################################################################################
# GNUmakefile for the input/output subsystem
#
# Change log:
# 18 March 2009 - Initial submission (Kareem)
#
################################################################################

name := io

include ../BaccConfig/Libraries.gmk
