################################################################################
# GNUmakefile for the processing subsystem
#
# Change log:
# 18 March 2009 - Initial submission (Kareem)
#
################################################################################

name := processing

include ../BaccConfig/Libraries.gmk
