####################################################################################################
# example macro for the LUXSim package                                                             #
#                                                                                                  #
# Change log:                                                                                      #
# 19 Aug 2013 - Initial submission (Vic)                                                           #
#                                                                                                  #
####################################################################################################
/run/verbose 1
/control/verbose 0
/tracking/verbose 0
/grdm/verbose 0
/process/verbose 0

## Set up visualization - Comment this stuff out if you want to skip visualization
###/vis/open OGLSQt 1200x1200-0+0
#/vis/open VRML2FILE
#/vis/drawVolume
#/vis/scene/add/trajectories
#/vis/scene/endOfEventAction accumulate
#/tracking/storeTrajectory 1
#/vis/viewer/set/viewpointVector 0.5 0.75 1
#/vis/viewer/set/upVector 0 0 1
#/vis/viewer/zoom 0 
##/vis/viewer/set/viewpointThetaPhi 45 45             
#/vis/viewer/set/style surface

# Set up visualization so that we don't cloud the issue with neutrinos - Comment this stuff out if you want to skip visualization
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add nu_e
#/vis/filtering/trajectories/particleFilter-0/add nu_mu
#/vis/filtering/trajectories/particleFilter-0/add nu_tau
#/vis/filtering/trajectories/particleFilter-0/add anti_nu_e
#/vis/filtering/trajectories/particleFilter-0/add anti_nu_mu
#/vis/filtering/trajectories/particleFilter-0/add anti_nu_tau
#/vis/filtering/trajectories/particleFilter-0/invert true

# Color keys: white, gray, grey, black, red, green, blue, cyan, magenta, yellow - Comment this stuff out if you want to skip visualization
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
#/vis/modeling/trajectories/drawByParticleID-0/set e- magenta
#/vis/modeling/trajectories/drawByParticleID-0/set proton cyan
#/vis/modeling/trajectories/drawByParticleID-0/set neutron grey
#/vis/modeling/trajectories/drawByParticleID-0/set gamma green
#/vis/modeling/trajectories/drawByParticleID-0/set opticalPhoton yellow

# This next set of lines is to, as it appears, initialize the simulation
/run/initialize

# Set the output directory
/Bacc/io/outputDir ./ 
#/p/lscratchh/naim1/DTSimulations/PastRootFiles/ScatteringTests/BackgroundTests/
#g/g14/naim1/BACCARAT/ 
#/p/lscratchh/naim1/DTSimulations/PastRootFiles/ScatteringTests/
#/g/g14/naim1/BACCARAT/ 
#/p/lscratchh/naim1/DTSimulations/Tests/bin_files/
/Bacc/io/outputName TEST
#BackgroundTest_Sheetinfrontofcollimator_10thousand14MeVNeutrons_Iso_20cmlead_36inchwater_

# FiftyThousandNeutronsOne_SixDifferentDegrees_LSWaterTankRadius80cm115cmDistanceRecordXenonandLS1MonoEnergeticBeam14MeV_StepSizeCut_
/Bacc/io/updateFrequency 5000


# Set the random seed
#/Bacc/randomSeed 0

# Select the kind of detector to use
/XeNeu/dtShieldingOn true
#/Bacc/detector/select simpleExample
#/Bacc/detector/select complexExample
#/Bacc/detector/select LLNLSinglePhase
/Bacc/detector/select XeNeuDTDetector
#/XeNeu/ddShieldingOn true

# Update geometry
/Bacc/detector/update

# Set the record level for one of the volumes to write some information about it
#/Bacc/detector/recordLevel LiquidXeTarget 2 # For "simpleExample" or "complexExample"
#/Bacc/detector/recordLevel activeVolume 2 # For "LLNLSinglePhase"

#record
/Bacc/detector/recordLevel liquid_xenon 2 # For "GNARRLIDetector"
/Bacc/detector/recordLevel outer_can 2 
/Bacc/detector/recordLevel vacuum_space 2
/Bacc/detector/recordLevel inner_can 2 
/Bacc/detector/recordLevel detector 2
/Bacc/detector/recordLevel LeadOutside 2
/Bacc/detector/recordLevel dt_shield 2
/Bacc/detector/recordLevel Teflon 2
/Bacc/detector/recordLevel DT_Tube 2
/Bacc/detector/recordLevel Lead 2
/Bacc/detector/recordLevel BPEShielding 2
/Bacc/detector/recordLevel Collimator 2
/Bacc/detector/recordLevel Water 2
/Bacc/detector/recordLevel PhotocathodeBottom 2

#/Bacc/detector/recordLevel liquid_xenon_target 3 
/Bacc/detector/recordLevel ls_detector_2
/Bacc/detector/recordLevel cathode_ring 2
/Bacc/detector/recordLevel field_ring 2
/Bacc/detector/recordLevel peek_rod 2
/Bacc/detector/recordLevel teflon 2
/Bacc/detector/recordLevel gas_xenon 2
/Bacc/detector/recordLevel bottom_pmt 2
/Bacc/detector/recordLevel pmt_al_box 2
/Bacc/detector/recordLevel glass_slide 2
/Bacc/detector/recordLevel bpe_outer_shield 2
/Bacc/detector/recordLevel pmt_teflon_casing 2
/Bacc/detector/recordLevel anode_holder 2
/Bacc/detector/recordLevel pmtCage 2 
/Bacc/detector/recordLevel detector 2
/Bacc/detector/recordLevel ls_target 2
/Bacc/detector/recordLevel tof_target 2
/Bacc/detector/recordLevel ls_detector_shell 2
/Bacc/detector/recordLevel tof_detector_shell 2
/Bacc/detector/recordLevel lead_wall 2
/Bacc/detector/recordLevel lead 2
/Bacc/detector/recordLevel pb 2
/Bacc/detector/recordLevel al_detector_support 2
/Bacc/detector/recordLevel al 2
/Bacc/detector/recordLevel steel 2
/Bacc/detector/recordLevel vacuum 2
#/Bacc/detector/recordLevel ls_detector_1 3
#/Bacc/detector/recordLevel ls_detector_3 3
#/Bacc/detector/recordLevel ls_detector_4 3
#/Bacc/detector/recordLevel ls_detector_5 3
#/Bacc/detector/recordLevel ls_detector_6 3
#/Bacc/detector/recordLevel ls_detector_7 3
#/Bacc/detector/recordLevel ls_detector_8 3
#/Bacc/detector/recordLevel ls_detector_9 3
#/Bacc/detector/recordLevel ls_detector_10 3
#/Bacc/detector/recordLevel ls_detector_11 3
#/Bacc/detector/recordLevel ls_detector_12 3
#/Bacc/detector/recordLevel ls_target 3
#/Bacc/detector/recordLevel water_tank_shield 3
#/Bacc/detector/recordLevel liquid_xenon_below_cathode 3
#/Bacc/detector/recordLevel liquid_xenon_above_eg 3
#
#/Bacc/detector/recordLevel Teflon_BelowCath_obj  3
#/Bacc/detector/recordLevel Teflon_Inside_Drift_obj 3
#/Bacc/detector/recordLevel Teflon_Ring_AboveEG_obj 3
#


##/Bacc/detector/recordLevel subtract_object 2

##/Bacc/detector/recordLevel Shield_Sphere_1_object 3 

/Bacc/detector/recordLevel Measurement_Volume_object 3

##/Bacc/detector/recordLevel dt_shield 3 
##/Bacc/detector/recordLevel Water_Tank_object  3
##/Bacc/detector/recordLevel Water_Tank_object 3
##/Bacc/detector/recordLevel BPE5_Top_Shielding_object 3


#/Bacc/detector/recordLevel cathode_ring 3 
#/Bacc/detector/recordLevel field_ring_1 3 
#/Bacc/detector/recordLevel field_ring_2 3 
#/Bacc/detector/recordLevel field_ring_3 3 
#/Bacc/detector/recordLevel extraction_grid 3 
#/Bacc/detector/recordLevel weir 3 
#/Bacc/detector/recordLevel teflon_block_minus_weir 3 
#/Bacc/detector/recordLevel gas_xenon_in_weir 3 
#/Bacc/detector/recordLevel peek_rod_1 3 
#/Bacc/detector/recordLevel peek_rod_1 3 
#/Bacc/detector/recordLevel peek_rod_1 3 
#/Bacc/detector/recordLevel gas_xenon 3 
#/Bacc/detector/recordLevel bottom_pmt 3 
#/Bacc/detector/recordLevel pmt_al_box 3 
#/Bacc/detector/recordLevel glass_slide 3 
#/Bacc/detector/recordLevel pmt_teflon_casing 3 
#/Bacc/detector/recordLevel anode_holder 3 
#/Bacc/detector/recordLevel pmtCage 3 
#/Bacc/detector/recordLevel detector 3 
#/Bacc/detector/recordLevel ls_detector_shell 3 
#
#/Bacc/detector/recordLevel al_baseplate 3
#/Bacc/detector/recordLevel al_detector_support_1 3
#/Bacc/detector/recordLevel al_detector_support_2 3
#/Bacc/detector/recordLevel al_detector_support_3 3
#
#/Bacc/detector/recordLevel Lead_Shielding_Collimator_object 3
#/Bacc/detector/recordLevel Lead_Shielding_object 3




#/Bacc/detector/recordLevel ls_target 2 
#/Bacc/detector/recordLevel ls_detector_1 2 
#/Bacc/detector/recordLevel ls_detector_2 2 
#/Bacc/detector/recordLevel poly_block_0 2 
#/Bacc/detector/recordLevel poly_block_1 2 
#/Bacc/detector/recordLevel poly_block_2 2 
#/Bacc/detector/recordLevel sm_poly_block_1 2 
#/Bacc/detector/recordLevel sm_poly_block_2 2 
#/Bacc/detector/recordLevel poly_block_3 2 
#/Bacc/detector/recordLevel poly_block_4 2 
#/Bacc/detector/recordLevel poly_block_5 2 
#/Bacc/detector/recordLevel poly_block_6 2 
#/Bacc/detector/recordLevel lead_ring_1 2 
#/Bacc/detector/recordLevel lead_ring_2 2 
#/Bacc/detector/recordLevel dd_generator 2 
#/Bacc/detector/recordLevel dd_castle 2 
#/Bacc/detector/recordLevel b_poly_sheet_0 2 
#/Bacc/detector/recordLevel b_poly_sheet_1 2 
#/Bacc/detector/recordLevel b_poly_sheet_2 2 
#/Bacc/detector/recordLevel b_poly_sheet_3 2 
#/Bacc/detector/recordLevel lead_sheet 2 
#/Bacc/detector/recordLevel b_poly_1 2 
#/Bacc/detector/recordLevel b_poly_sheet_0 2 
#/Bacc/detector/recordLevel b_poly_sheet_1 2 
#/Bacc/detector/recordLevel lead_sheet_1 2 
#/Bacc/detector/recordLevel lead_sheet_2 2 
#/Bacc/detector/recordLevel b_poly_2 2 



/gps/particle neutron
/gps/energy 14 MeV
/gps/ene/type Mono
#/gps/ene/sigma .1 MeV
/gps/position 1.8 0. 0. m
#/gps/direction -1 0 0
/gps/ang/type iso
/gps/ang/mintheta 0. deg
/gps/ang/maxtheta 3. deg
/gps/ang/rot1 0 0 1
/gps/ang/rot2 0 -1 0
#/gps/ang/mintheta 0. deg
#/gps/ang/maxtheta 20. deg
#/gps/ang/minphi 160. deg
#/gps/ang/maxphi 200. deg
#/gps/ang/rot1 0 1 0
#/gps/ang/rot2 0 0 1


/Bacc/physicsList/useOpticalProcesses 0

/Bacc/beamOn 50000

exit
