####################################################################################################
# example macro for the LUXSim package                                                             #
#                                                                                                  #
# Change log:                                                                                      #
# 19 Aug 2013 - Initial submission (Vic)                                                           #
#                                                                                                  #
####################################################################################################
/run/verbose 1
/control/verbose 0
/tracking/verbose 0  
/grdm/verbose 0
/process/verbose 0

# Set up visualization - Comment this stuff out if you want to skip visualization
#/vis/open OGLSQt 1200x1200-0+0
#/vis/open VRML2FILE
#/vis/drawVolume
#/vis/scene/add/trajectories
#/vis/scene/endOfEventAction accumulate
#/tracking/storeTrajectory 1
#/vis/viewer/set/viewpointVector 0.5 0.75 1
#/vis/viewer/set/upVector 0 0 1
#/vis/viewer/zoom 0 
#/vis/viewer/set/viewpointThetaPhi 45 45             
#/vis/viewer/set/style surface

# Set up visualization so that we don't cloud the issue with neutrinos - Comment this stuff out if you want to skip visualization
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add nu_e
#/vis/filtering/trajectories/particleFilter-0/add nu_mu
#/vis/filtering/trajectories/particleFilter-0/add nu_tau
#/vis/filtering/trajectories/particleFilter-0/add anti_nu_e
#/vis/filtering/trajectories/particleFilter-0/add anti_nu_mu
#/vis/filtering/trajectories/particleFilter-0/add anti_nu_tau
#/vis/filtering/trajectories/particleFilter-0/invert true

# Color keys: white, gray, grey, black, red, green, blue, cyan, magenta, yellow - Comment this stuff out if you want to skip visualization
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
#/vis/modeling/trajectories/drawByParticleID-0/set e- magenta
#/vis/modeling/trajectories/drawByParticleID-0/set proton cyan
#/vis/modeling/trajectories/drawByParticleID-0/set neutron grey
#/vis/modeling/trajectories/drawByParticleID-0/set gamma green
#/vis/modeling/trajectories/drawByParticleID-0/set opticalPhoton yellow

# This next set of lines is to, as it appears, initialize the simulation
/run/initialize

# Set the output directory
/Bacc/io/outputDir /p/lscratchd/lenardo1/XeNeu/Simulations/batch_test
/Bacc/io/outputName XeNeu_350pm15keVneutrons_square_surface_beam_no_shielding_peek_weir_
/Bacc/io/updateFrequency 10000


# Set the random seed
#/Bacc/randomSeed 0

# Select the kind of detector to use
#/Bacc/detector/select simpleExample
#/Bacc/detector/select complexExample
#/Bacc/detector/select LLNLSinglePhase
/Bacc/detector/select XeNeuDetector

# Update geometry
/Bacc/detector/update

# Set the record level for one of the volumes to write some information about it
#/Bacc/detector/recordLevel LiquidXeTarget 2 # For "simpleExample" or "complexExample"
#/Bacc/detector/recordLevel activeVolume 2 # For "LLNLSinglePhase"
/Bacc/detector/recordLevel outer_can 2 
/Bacc/detector/recordLevel vacuum_space 2 
/Bacc/detector/recordLevel inner_can 2 
/Bacc/detector/recordLevel liquid_xenon 2 
/Bacc/detector/recordLevel cathode_ring 2 
/Bacc/detector/recordLevel field_ring_1 2 
/Bacc/detector/recordLevel field_ring_2 2 
/Bacc/detector/recordLevel field_ring_3 2 
/Bacc/detector/recordLevel extraction_grid 2 
/Bacc/detector/recordLevel weir 2 
/Bacc/detector/recordLevel teflon_block_minus_weir 2 
/Bacc/detector/recordLevel gas_xenon_in_weir 2 
/Bacc/detector/recordLevel peek_rod_1 2 
/Bacc/detector/recordLevel peek_rod_2 2 
/Bacc/detector/recordLevel peek_rod_3 2 
/Bacc/detector/recordLevel gas_xenon 2 
/Bacc/detector/recordLevel bottom_pmt 2 
/Bacc/detector/recordLevel pmt_al_box 2 
/Bacc/detector/recordLevel glass_slide 2 
/Bacc/detector/recordLevel pmt_teflon_casing 2 
/Bacc/detector/recordLevel anode_holder 2 
/Bacc/detector/recordLevel pmtCage 2 
/Bacc/detector/recordLevel detector 2 
/Bacc/detector/recordLevel al_detector_support_1 2 
/Bacc/detector/recordLevel al_detector_support_2 2 
/Bacc/detector/recordLevel al_detector_support_3 2 
/Bacc/detector/recordLevel steel_vacuum_box 2 
/Bacc/detector/recordLevel steel_CF_flanges 2 
/Bacc/detector/recordLevel vacuum_box 2 
/Bacc/detector/recordLevel al_baseplate 2 


# This can be used in place of the regular the event generators. Be sure you
# know what you're doing if you're going to use commands like these.
#/gps/particle e-
/gps/particle neutron
#/gps/particle geantino
#/gps/energy 0.015 MeV
/gps/energy 0.35 MeV
/gps/ene/type Gauss
#/gps/ene/sigma 0.015 MeV
/gps/ene/sigma 0.1 MeV

/Bacc/physicsList/useOpticalProcesses 0

#/gps/position 0 0 0.022 m
/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/halfy 1.168 cm
/gps/pos/halfx 2.5 cm
/gps/pos/centre +0.42 0 -0.00185 m
/gps/pos/rot1 0 1 0
/gps/pos/rot2 0 0 1 

/gps/direction -1 0 0 
#/gps/ang/rot1 1 0 0
#/gps/ang/mintheta 89.99 deg
#/gps/ang/maxtheta 90.01 deg
#/gps/ang/rot1 1 0 0
#/gps/ang/rot2 0 1 0
/Bacc/beamOn 100
#/Bacc/beamOn 5
exit
