####################################################################################################
# example macro for the LUXSim package                                                             #
#                                                                                                  #
# Change log:                                                                                      #
# 19 Aug 2013 - Initial submission (Vic)                                                           #
#                                                                                                  #
####################################################################################################
/run/verbose 1
/control/verbose 0
/tracking/verbose 1
/grdm/verbose 0
/process/verbose 1


## Set up visualization - Comment this stuff out if you want to skip visualization
###/vis/open OGLSQt 1200x1200-0+0
#/vis/open VRML2FILE
#/vis/drawVolume
#/vis/scene/add/trajectories
#/vis/scene/endOfEventAction accumulate
#/tracking/storeTrajectory 1
#/vis/viewer/set/viewpointVector 0.5 0.75 1
#/vis/viewer/set/upVector 0 0 1
#/vis/viewer/zoom 0 
#/vis/viewer/set/viewpointThetaPhi 45 45             
#/vis/viewer/set/style surface

# Set up visualization so that we don't cloud the issue with neutrinos - Comment this stuff out if you want to skip visualization
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add nu_e
#/vis/filtering/trajectories/particleFilter-0/add nu_mu
#/vis/filtering/trajectories/particleFilter-0/add nu_tau
#/vis/filtering/trajectories/particleFilter-0/add anti_nu_e
#/vis/filtering/trajectories/particleFilter-0/add anti_nu_mu
#/vis/filtering/trajectories/particleFilter-0/add anti_nu_tau
#/vis/filtering/trajectories/particleFilter-0/invert true

# Color keys: white, gray, grey, black, red, green, blue, cyan, magenta, yellow - Comment this stuff out if you want to skip visualization
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
#/vis/modeling/trajectories/drawByParticleID-0/set e- magenta
#/vis/modeling/trajectories/drawByParticleID-0/set proton cyan
#/vis/modeling/trajectories/drawByParticleID-0/set neutron grey
#/vis/modeling/trajectories/drawByParticleID-0/set gamma green
#/vis/modeling/trajectories/drawByParticleID-0/set opticalPhoton yellow

# This next set of lines is to, as it appears, initialize the simulation

/run/initialize

# Set the output directory
/Bacc/io/outputDir ./
/Bacc/io/outputName visualtest_
#OpticalPhotonNoTeflon10000events_neg15mminZ_gasxenonmeasurement_StraightUP 
#OpticalPhoton_3000Events_AboveEGPosition_PMTPhotoCathodeSensitiveVolume_withaddedteflon_
/Bacc/io/updateFrequency 10000



# Set the random seed
#/Bacc/randomSeed 1443996789
#/Bacc/randomSeed 2
#Event seeds (idx,1,2): (4,1689174239,709645262)
/Bacc/inputEventRandomSeed true
/Bacc/eventSeedIndex 27
/Bacc/eventSeed1 611767323
/Bacc/eventSeed2 1459778372
# iEventSeedIndex = 26
# iEventSeed1     = 911874496
# iEventSeed2     = 1993247747

# iEventSeed1     = 1799435490
# iEventSeed2     = 1866894232
# iEventSeedIndex = 202
# iEventSeed1     = 1878352554
# iEventSeed2     = 898339343
#(93,160046346,1376205460)
# iEventSeedIndex = 148
# iEventSeed1     = 1471237935
# iEventSeed2     = 1808106101
#(89,156131120,792071204)
#(2,1111758524,1807838028)
#(2,1433648226,1870278457)
#(106,1409112465,2141943786)
#(106,452103759,824512441)

# Select the kind of detector to use
/XeNeu/dtShieldingOn true
#/Bacc/detector/select simpleExample
#/Bacc/detector/select complexExample
#/Bacc/detector/select LLNLSinglePhase
/Bacc/detector/select XeNeuDTDetector
#/XeNeu/ddShieldingOn true

# Update geometry
/Bacc/detector/update

/Bacc/detector/recordLevel liquid_xenon 2 # For "GNARRLIDetector"
/Bacc/detector/recordLevel outer_can 2 
/Bacc/detector/recordLevel vacuum_space 2
/Bacc/detector/recordLevel inner_can 2 
/Bacc/detector/recordLevel detector 2
/Bacc/detector/recordLevel dt_shield 2
/Bacc/detector/recordLevel Teflon 2
/Bacc/detector/recordLevel DT_Tube 2
/Bacc/detector/recordLevel Lead 2
/Bacc/detector/recordLevel BPEShielding 2
/Bacc/detector/recordLevel Collimator 2
/Bacc/detector/recordLevel Water 2
/Bacc/detector/recordLevel PhotocathodeBottom 2

/Bacc/detector/recordLevel cathode_ring 2
/Bacc/detector/recordLevel field_ring 2
/Bacc/detector/recordLevel peek_rod 2
/Bacc/detector/recordLevel teflon 2
/Bacc/detector/recordLevel gas_xenon 2
/Bacc/detector/recordLevel bottom_pmt 2
/Bacc/detector/recordLevel pmt_al_box 2
/Bacc/detector/recordLevel glass_slide 2
/Bacc/detector/recordLevel pmt_teflon_casing 2
/Bacc/detector/recordLevel anode_holder 2
/Bacc/detector/recordLevel pmtCage 2 
/Bacc/detector/recordLevel ls_target 2
/Bacc/detector/recordLevel ls_detector_shell 2
/Bacc/detector/recordLevel pb 2
/Bacc/detector/recordLevel al_detector_support 2
/Bacc/detector/recordLevel al_baseplate 2
/Bacc/detector/recordLevel steel 2
/Bacc/detector/recordLevel vacuum 2



/gps/particle neutron
/gps/energy 14.1 MeV
/gps/ene/type Mono
#/gps/ene/sigma 0.23 eV
/gps/position 1.52 0. 0. m
#/gps/direction -1 0 0
/gps/ang/type iso
/gps/ang/mintheta 0. deg
/gps/ang/maxtheta 0.5 deg
/gps/ang/rot1 0 0 1
/gps/ang/rot2 0 -1 0
#/gps/ang/mintheta 0. deg
#/gps/ang/maxtheta 140. deg
#/gps/pos/type Point
#/gps/pos/centre 0 0 0 mm
#/gps/direction 0 0 -1


/Bacc/physicsList/useOpticalProcesses 0
#/Bacc/physicsList/opticalDebug true 

/Bacc/beamOn 1

exit
