/run/verbose 1
/control/verbose 0
/tracking/verbose 1
/grdm/verbose 0
/process/verbose 0


# Set up visualization - Comment this stuff out if you want to skip visualization
##/vis/open OGLSQt 1200x1200-0+0
/vis/open VRML2FILE
/vis/drawVolume
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate
/tracking/storeTrajectory 1
/vis/viewer/set/viewpointVector 0.5 0.75 1
/vis/viewer/set/upVector 0 0 1
/vis/viewer/zoom 0 
#/vis/viewer/set/viewpointThetaPhi 45 45             
/vis/viewer/set/style surface


/run/initialize

# Set the output directory
/Bacc/io/outputDir ./
/Bacc/io/outputName visualtest_
#OpticalPhotonNoTeflon10000events_neg15mminZ_gasxenonmeasurement_StraightUP 
#OpticalPhoton_3000Events_AboveEGPosition_PMTPhotoCathodeSensitiveVolume_withaddedteflon_
/Bacc/io/updateFrequency 10000


# Set the random seed
/Bacc/randomSeed 4


#/XeNeu/dtShieldingOn true
/Bacc/detector/select XeNeuDTDetector
/Bacc/detector/update

#/Bacc/detector/recordLevel liquid_xenon_target 3 
#/Bacc/detector/recordLevel liquid_xenon_below_cathode 3
#/Bacc/detector/recordLevel liquid_xenon_above_eg 3 
#/Bacc/detector/recordLevel gas_xenon 3

#/Bacc/detector/recordLevel liquid_xenon_target 3


/gps/particle neutron
#/gps/particle geantino
/gps/energy 2.45 MeV
/gps/ene/type Mono
#/gps/ene/sigma 0.23 eV
/gps/position 70.72 0. 0. cm
#/gps/direction -1 0 0
/gps/ang/type iso
/gps/ang/mintheta 0. deg
/gps/ang/maxtheta 0.001 deg
/gps/ang/rot1 0 0 1
/gps/ang/rot2 0 -1 0
#/gps/ang/mintheta 0. deg
#/gps/ang/maxtheta 140. deg
#/gps/pos/type Point
#/gps/pos/centre 0 0 0 mm
#/gps/direction 0 0 -1

/Bacc/physicsList/useOpticalProcesses 0
#/Bacc/physicsList/opticalDebug true 

/Bacc/beamOn 3

exit
