////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define Mossbauer geometry
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

#ifndef MossbauerDetector_HH
#define MossbauerDetector_HH 1

//
//      GEANT4 includes
//
#include "globals.hh"

//
//      BACCARAT includes
//
#include "BaccDetector.hh"
#include "BaccManager.hh"

//
//	Project-specific includes
//
#include "MossbauerDetectorParameters.hh"

//
//      Class forwarding
//
class G4LogicalVolume;
class BaccDetectorComponent;
class G4NistManager;
class BaccMaterials;
class MossbauerMessenger;
class MossbauerMaterials;

//------++++++------++++++------++++++------++++++------++++++------++++++------
class MossbauerDetector : public BaccDetector
{
public:
  MossbauerDetector( G4String, G4String );
  ~MossbauerDetector();
  
  void BuildDetector();
  G4ThreeVector SetOrigin(BaccDetectorComponent *);
  void InitializeDetector();

  //  Registration methods below

  
private:
  MossbauerMessenger *Mossbauermessenger;
  MossbauerMaterials *Mossbauermaterials;
  G4NistManager *NISTmaterials;
  BaccMaterials *BACCmaterials;
  
};

#endif
