################################################################################
# GNUmakefile for the management subsystem
#
# Change log:
# 18 March 2009 - Initial submission (Kareem)
#
################################################################################

name := management

include ../BaccConfig/Libraries.gmk
