////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define AmBeXe127Source parameters
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

#ifndef AmBeXe127SourceDetectorParameters_h
#define AmBeXe127SourceDetectorParameters_h 1

#include "G4SystemOfUnits.hh"

namespace AmBeXe127SourceDetectorParameters{
  
  //define your detector parameters here
  
}

#endif
