////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define the messenger
// commands for the AmBeXe127Source project.
// All geometry, physics, io managements, etc, happen here
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

#ifndef AmBeXe127SourceMessenger_HH
#define AmBeXe127SourceMessenger_HH 1

//
//      GEANT4 includes
//
#include "globals.hh"
#include "G4UImessenger.hh"

//
//      Class forwarding
//
class G4UIdirectory;
// Uncomment the class that you will need
//class G4UicmdWithAnInteger;
//class G4UicmdWithoutParameter;
//class G4UicmdWithAString;
//class G4UicmdWithABool;
//class G4UIcmdWithADoubleAndUnit;
//class G4UicmdWithADouble;

class AmBeXe127SourceDetector;

//------++++++------++++++------++++++------++++++------++++++------++++++------
class AmBeXe127SourceMessenger : public G4UImessenger
{
public:
  AmBeXe127SourceMessenger( AmBeXe127SourceDetector* );
  ~AmBeXe127SourceMessenger();
  
  void SetNewValue( G4UIcommand*, G4String );
  
private:
  AmBeXe127SourceDetector *AmBeXe127Sourcedetector;
  
  //      The directory
  G4UIdirectory *AmBeXe127SourceDir;

  // Declare the UI commands below
  
};

#endif
