////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define the messenger
// commands for the Xe127Radioassay project.
// All geometry, physics, io managements, etc, happen here
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

//
//	GEANT4 includes
//
#include "G4UIdirectory.hh"
// uncomment the headers that you will need
//#include "G4UIcmdWithAnInteger.hh"
//#include "G4UIcmdWithoutParameter.hh"
//#include "G4UIcmdWithAString.hh"
//#include "G4UIcmdWithABool.hh"
//#include "G4UIcmdWith3VectorAndUnit.hh"
//#include "G4UIcmdWithADoubleAndUnit.hh"
//#include "G4UIcmdWith3Vector.hh"
//#include "G4UIcmdWithADouble.hh"
#include "globals.hh"

//
// Project-specific includes
//
#include "Xe127RadioassayMessenger.hh"
#include "Xe127RadioassayDetector.hh"

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					Messenger()
//------++++++------++++++------++++++------++++++------++++++------++++++------
Xe127RadioassayMessenger::Xe127RadioassayMessenger( Xe127RadioassayDetector *Det )
  : Xe127Radioassaydetector( Det )
{
  //  Set up the directory
  Xe127RadioassayDir = new G4UIdirectory( "/Xe127Radioassay/" );
  Xe127RadioassayDir->SetGuidance( "All Xe127Radioassay project commands are contained under /Xe127Radioassay/" );

}

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					~Messenger()
//------++++++------++++++------++++++------++++++------++++++------++++++------
Xe127RadioassayMessenger::~Xe127RadioassayMessenger()
{
  //delete everything that you declared with new
  delete Xe127RadioassayDir;

}

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					SetNewValue()
//------++++++------++++++------++++++------++++++------++++++------++++++------
void Xe127RadioassayMessenger::SetNewValue( G4UIcommand *command, G4String newValue )
{
  
}

