////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define DuMmYkEy geometry
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

#ifndef DuMmYkEyDetector_HH
#define DuMmYkEyDetector_HH 1

//
//      GEANT4 includes
//
#include "globals.hh"

//
//      BACCARAT includes
//
#include "BaccDetector.hh"
#include "BaccManager.hh"

//
//	Project-specific includes
//
#include "DuMmYkEyDetectorParameters.hh"

//
//      Class forwarding
//
class G4LogicalVolume;
class BaccDetectorComponent;
class G4NistManager;
class BaccMaterials;
class DuMmYkEyMessenger;
class DuMmYkEyMaterials;

//------++++++------++++++------++++++------++++++------++++++------++++++------
class DuMmYkEyDetector : public BaccDetector
{
public:
  DuMmYkEyDetector( G4String, G4String );
  ~DuMmYkEyDetector();
  
  void BuildDetector();
  G4ThreeVector SetOrigin(BaccDetectorComponent *);
  void InitializeDetector();

  //  Registration methods below

  
private:
  DuMmYkEyMessenger *DuMmYkEymessenger;
  DuMmYkEyMaterials *DuMmYkEymaterials;
  G4NistManager *NISTmaterials;
  BaccMaterials *BACCmaterials;
  
};

#endif
