////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define KTonXe geometry
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

#ifndef KTonXeDetector_HH
#define KTonXeDetector_HH 1

//
//      GEANT4 includes
//
#include "globals.hh"

//
//      BACCARAT includes
//
#include "BaccDetector.hh"
#include "BaccManager.hh"

//
//	Project-specific includes
//
#include "KTonXeDetectorParameters.hh"

//
//      Class forwarding
//
class G4LogicalVolume;
class BaccDetectorComponent;
class G4NistManager;
class BaccMaterials;
class KTonXeMessenger;
class KTonXeMaterials;

//------++++++------++++++------++++++------++++++------++++++------++++++------
class KTonXeDetector : public BaccDetector
{
public:
  KTonXeDetector( G4String, G4String );
  ~KTonXeDetector();
  
  void BuildDetector();
  G4ThreeVector SetOrigin(BaccDetectorComponent *);
  void InitializeDetector();

  //  Registration methods below

  
private:
  KTonXeMessenger *KTonXemessenger;
  KTonXeMaterials *KTonXematerials;
  G4NistManager *NISTmaterials;
  BaccMaterials *BACCmaterials;
  
};

#endif
