################################################################################
# GNUmakefile for the geometry subsystem
#
# Change log:
# 18 March 2009 - Initial submission (Kareem)
# 14 January 2016 - Add functionality to create sources codes that automatically
#                   detect and include new projects (Jingke)
#
################################################################################

name := geometry

include ../BaccConfig/Libraries.gmk
include ../BaccConfig/BuildCatalog.gmk
