////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define Xe127Radioassay geometry
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

#ifndef Xe127RadioassayDetector_HH
#define Xe127RadioassayDetector_HH 1

//
//      GEANT4 includes
//
#include "globals.hh"

//
//      BACCARAT includes
//
#include "BaccDetector.hh"
#include "BaccManager.hh"

//
//	Project-specific includes
//
#include "Xe127RadioassayDetectorParameters.hh"

//
//      Class forwarding
//
class G4LogicalVolume;
class BaccDetectorComponent;
class G4NistManager;
class BaccMaterials;
class Xe127RadioassayMessenger;
class Xe127RadioassayMaterials;

//------++++++------++++++------++++++------++++++------++++++------++++++------
class Xe127RadioassayDetector : public BaccDetector
{
public:
  Xe127RadioassayDetector( G4String, G4String );
  ~Xe127RadioassayDetector();
  
  void BuildDetector();
  G4ThreeVector SetOrigin(BaccDetectorComponent *);
  void InitializeDetector();

  //  Registration methods below

  
private:
  Xe127RadioassayMessenger *Xe127Radioassaymessenger;
  Xe127RadioassayMaterials *Xe127Radioassaymaterials;
  G4NistManager *NISTmaterials;
  BaccMaterials *BACCmaterials;
  
};

#endif
