////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define Xe127Radioassay parameters
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

#ifndef Xe127RadioassayDetectorParameters_h
#define Xe127RadioassayDetectorParameters_h 1

#include "G4SystemOfUnits.hh"

namespace Xe127RadioassayDetectorParameters{
  
  //define your detector parameters here
  
}

#endif
