////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define the messenger
// commands for the Xe127Radioassay project.
// All geometry, physics, io managements, etc, happen here
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

#ifndef Xe127RadioassayMessenger_HH
#define Xe127RadioassayMessenger_HH 1

//
//      GEANT4 includes
//
#include "globals.hh"
#include "G4UImessenger.hh"

//
//      Class forwarding
//
class G4UIdirectory;
// Uncomment the class that you will need
//class G4UicmdWithAnInteger;
//class G4UicmdWithoutParameter;
//class G4UicmdWithAString;
//class G4UicmdWithABool;
//class G4UIcmdWithADoubleAndUnit;
//class G4UicmdWithADouble;

class Xe127RadioassayDetector;

//------++++++------++++++------++++++------++++++------++++++------++++++------
class Xe127RadioassayMessenger : public G4UImessenger
{
public:
  Xe127RadioassayMessenger( Xe127RadioassayDetector* );
  ~Xe127RadioassayMessenger();
  
  void SetNewValue( G4UIcommand*, G4String );
  
private:
  Xe127RadioassayDetector *Xe127Radioassaydetector;
  
  //      The directory
  G4UIdirectory *Xe127RadioassayDir;

  // Declare the UI commands below
  
};

#endif
