////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define AmBeXe137Source parameters
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

#ifndef AmBeXe137SourceDetectorParameters_h
#define AmBeXe137SourceDetectorParameters_h 1

#include "G4SystemOfUnits.hh"

namespace AmBeXe137SourceDetectorParameters{
  
  //define your detector parameters here
  
}

#endif
