////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define GammaEfficiencies materials
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

#ifndef GammaEfficienciesMaterials_HH
#define GammaEfficienciesMaterials_HH 1

//
//	c++ includes
//
#include <map>

//
//	Geant4 includes
//
#include "G4String.hh"

//
//	Class forwarding
//
class G4Material;
class G4VisAttributes;
//class G4MaterialPropertiesTable;
class G4OpticalSurface;

typedef std::map<G4String, G4Material*> material_map;
//typedef std::map<G4String, G4MaterialPropertiesTable*> property_map;
typedef std::map<G4String, G4VisAttributes*> vis_map;
typedef std::map<G4String, G4OpticalSurface*> optical_map;

//------++++++------++++++------++++++------++++++------++++++------++++++------
class GammaEfficienciesMaterials
{
public:
  GammaEfficienciesMaterials();
  ~GammaEfficienciesMaterials();
  
  static GammaEfficienciesMaterials *GetInstance();
  
  G4Material *GetMaterialByName(G4String);
  G4VisAttributes *GetVisAttributesByName(G4String);
  //  G4MaterialPropertiesTable *GetPropertiesTableByName(G4String);
  G4OpticalSurface *GetOpticalSurfaceByName(G4String);
  
  inline G4Material* LiquidXe() { return liquidXe; }
  inline G4Material* GammaEfficiencies() { return tms; }
  inline G4Material* Paraffin() { return paraffin; }
  inline G4Material* BoratedWater() { return boratedWater; }
  inline G4Material* BoratedPoly10() { return boratedPoly10; }
  inline G4Material* BoratedPoly20() { return boratedPoly20; }
  inline G4Material* BoratedPoly30() { return boratedPoly30; }
  inline G4Material* SodiumIodide() { return sodiumIodide; }
  inline G4Material* LaBr3() { return lanthanumBromide; }
 
  inline G4VisAttributes* LiquidXeVis() { return liquidXeVis; }
  inline G4VisAttributes* GammaEfficienciesVis() { return tmsVis; } 
  inline G4VisAttributes* ParaffinVis() { return paraffinVis; }
  inline G4VisAttributes* BoratedWaterVis() { return boratedWaterVis; }
  inline G4VisAttributes* BoratedPoly10Vis() { return boratedPoly10Vis; }
  inline G4VisAttributes* BoratedPoly20Vis() { return boratedPoly20Vis; }
  inline G4VisAttributes* BoratedPoly30Vis() { return boratedPoly30Vis; }
  inline G4VisAttributes* SodiumIodideVis() { return sodiumIodideVis; }
  inline G4VisAttributes* LaBr3Vis() { return lanthanumBromideVis; }


private:
  
  static GammaEfficienciesMaterials *GammaEfficienciesmaterials;
  
  material_map materials;
  //  property_map properties;
  vis_map visattributes;
  optical_map opticals;
  
  void CreateMaterials();
  void CreateOpticalSurfaces();
  void CreateVisualAttributes();

  G4Material* liquidXe;
  G4Material* tms;
  G4Material * boratedWater;
  G4Material * paraffin;
  G4Material * boratedPoly10;
  G4Material * boratedPoly20;
  G4Material * boratedPoly30; 
  G4Material * sodiumIodide; 
  G4Material * lanthanumBromide; 

  G4VisAttributes* liquidXeVis;
  G4VisAttributes* tmsVis;
  G4VisAttributes* boratedWaterVis;
  G4VisAttributes* paraffinVis;
  G4VisAttributes* boratedPoly10Vis;
  G4VisAttributes* boratedPoly20Vis;
  G4VisAttributes* boratedPoly30Vis;
  G4VisAttributes* sodiumIodideVis;
  G4VisAttributes* lanthanumBromideVis;

};

#endif
