////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define GammaEfficiencies geometry
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

#ifndef GammaEfficienciesDetector_HH
#define GammaEfficienciesDetector_HH 1

//
//      GEANT4 includes
//
#include "globals.hh"

//
//      BACCARAT includes
//
#include "BaccDetector.hh"
#include "BaccManager.hh"

//
//	Project-specific includes
//

//
//      Class forwarding
//
class G4LogicalVolume;
class BaccDetectorComponent;
class G4NistManager;
class BaccMaterials;
class GammaEfficienciesMessenger;
class GammaEfficienciesMaterials;
class TestShieldMaterials;

//------++++++------++++++------++++++------++++++------++++++------++++++------
class GammaEfficienciesDetector : public BaccDetector
{
public:
  GammaEfficienciesDetector( G4String, G4String );
  ~GammaEfficienciesDetector();
  
  void BuildDetector();
  G4ThreeVector SetOrigin(BaccDetectorComponent *);
  void InitializeDetector();

  //  Registration methods below
  void SetShieldingRadius( G4double val ) { shieldingRadius = val; }
  
private:
  GammaEfficienciesMessenger *GammaEfficienciesmessenger;
  GammaEfficienciesMaterials *GammaEfficienciesmaterials;
  G4NistManager *NISTmaterials;
  BaccMaterials *BACCmaterials;
  TestShieldMaterials * TestShieldmaterials; 

  G4double shieldingRadius;
  
};

#endif
