////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define GammaEfficiencies parameters
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

#ifndef GammaEfficienciesDetectorParameters_h
#define GammaEfficienciesDetectorParameters_h 1

#include "G4SystemOfUnits.hh"

namespace GammaEfficienciesDetectorParameters{
  
  //define your detector parameters here
  
}

#endif
