////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define NeutronAttenuationTest parameters
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

#ifndef NeutronAttenuationTestDetectorParameters_h
#define NeutronAttenuationTestDetectorParameters_h 1

#include "G4SystemOfUnits.hh"

namespace NeutronAttenuationTestDetectorParameters{
  
  //define your detector parameters here
  
}

#endif
