////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define NeutronAttenuationTest geometry
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

#ifndef NeutronAttenuationTestDetector_HH
#define NeutronAttenuationTestDetector_HH 1

//
//      GEANT4 includes
//
#include "globals.hh"

//
//      BACCARAT includes
//
#include "BaccDetector.hh"
#include "BaccManager.hh"

//
//	Project-specific includes
//

//
//      Class forwarding
//
class G4LogicalVolume;
class BaccDetectorComponent;
class G4NistManager;
class BaccMaterials;
class NeutronAttenuationTestMessenger;
class NeutronAttenuationTestMaterials;

//------++++++------++++++------++++++------++++++------++++++------++++++------
class NeutronAttenuationTestDetector : public BaccDetector
{
public:
  NeutronAttenuationTestDetector( G4String, G4String );
  ~NeutronAttenuationTestDetector();
  
  void BuildDetector();
  G4ThreeVector SetOrigin(BaccDetectorComponent *);
  void InitializeDetector();

  //  Registration methods below
  void SetShieldingThickness( G4double val ) { shieldingThickness = val; }
  
private:
  NeutronAttenuationTestMessenger *NeutronAttenuationTestmessenger;
  NeutronAttenuationTestMaterials *NeutronAttenuationTestmaterials;
  G4NistManager *NISTmaterials;
  BaccMaterials *BACCmaterials;
 
  G4double shieldingThickness;
  
};

#endif
