////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define the messenger
// commands for the XeNeu project.
// All geometry, physics, io managements, etc, happen here
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

#ifndef XeNeuMessenger_HH
#define XeNeuMessenger_HH 1

//
//      GEANT4 includes
//
#include "globals.hh"
#include "G4UImessenger.hh"

//
//      Class forwarding
//
class G4UIdirectory;
// Uncomment the class that you will need
//class G4UicmdWithAnInteger;
//class G4UicmdWithoutParameter;
//class G4UicmdWithAString;
class G4UIcmdWithABool;
//class G4UIcmdWithADoubleAndUnit;
class G4UIcmdWithADouble;

class XeNeuDetector;

//------++++++------++++++------++++++------++++++------++++++------++++++------
class XeNeuMessenger : public G4UImessenger
{
public:
  XeNeuMessenger( XeNeuDetector* );
  ~XeNeuMessenger();
  
  void SetNewValue( G4UIcommand*, G4String );
  
private:
  XeNeuDetector *XeNeudetector;
  
  //      The directory
  G4UIdirectory *XeNeuDir;

  // Declare the UI commands below
  G4UIcmdWithABool * XeNeuDDShieldingCommand;
  G4UIcmdWithABool * XeNeuTOFCalibrationCommand;
  G4UIcmdWithABool * XeNeuMigdalNaITaggingCommand;
  G4UIcmdWithABool * XeNeuMigdalNeutronTaggingCommand;
  G4UIcmdWithADouble * XeNeuTOFDistanceCommand;

 
};

#endif
