////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define HVeV geometry
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

#ifndef HVeVDetector_HH
#define HVeVDetector_HH 1

//
//      GEANT4 includes
//
#include "globals.hh"

//
//      BACCARAT includes
//
#include "BaccDetector.hh"
#include "BaccManager.hh"

//
//	Project-specific includes
//
#include "HVeVDetectorParameters.hh"

//
//      Class forwarding
//
class G4LogicalVolume;
class BaccDetectorComponent;
class G4NistManager;
class BaccMaterials;
class HVeVMessenger;
class HVeVMaterials;

//------++++++------++++++------++++++------++++++------++++++------++++++------
class HVeVDetector : public BaccDetector
{
public:
  HVeVDetector( G4String, G4String );
  ~HVeVDetector();
  
  void BuildDetector();
  G4ThreeVector SetOrigin(BaccDetectorComponent *);
  void InitializeDetector();

  //  Registration methods below

  
private:
  HVeVMessenger *HVeVmessenger;
  HVeVMaterials *HVeVmaterials;
  G4NistManager *NISTmaterials;
  BaccMaterials *BACCmaterials;
  
};

#endif
