////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define the messenger
// commands for the ThermalFluxCalc project.
// All geometry, physics, io managements, etc, happen here
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

//
//	GEANT4 includes
//
#include "G4UIdirectory.hh"
// uncomment the headers that you will need
//#include "G4UIcmdWithAnInteger.hh"
//#include "G4UIcmdWithoutParameter.hh"
//#include "G4UIcmdWithAString.hh"
//#include "G4UIcmdWithABool.hh"
//#include "G4UIcmdWith3VectorAndUnit.hh"
#include "G4UIcmdWithADoubleAndUnit.hh"
//#include "G4UIcmdWith3Vector.hh"
//#include "G4UIcmdWithADouble.hh"
#include "globals.hh"

//
// Project-specific includes
//
#include "ThermalFluxCalcMessenger.hh"
#include "ThermalFluxCalcDetector.hh"

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					Messenger()
//------++++++------++++++------++++++------++++++------++++++------++++++------
ThermalFluxCalcMessenger::ThermalFluxCalcMessenger( ThermalFluxCalcDetector *Det )
  : ThermalFluxCalcdetector( Det )
{
  //  Set up the directory
  ThermalFluxCalcDir = new G4UIdirectory( "/ThermalFluxCalc/" );
  ThermalFluxCalcDir->SetGuidance( "All ThermalFluxCalc project commands are contained under /ThermalFluxCalc/" );
  
  ShieldingRadiusCommand = new G4UIcmdWithADoubleAndUnit( "/ThermalFluxCalc/shieldingRadius", this );
  ShieldingRadiusCommand->AvailableForStates( G4State_PreInit, G4State_Idle );

}

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					~Messenger()
//------++++++------++++++------++++++------++++++------++++++------++++++------
ThermalFluxCalcMessenger::~ThermalFluxCalcMessenger()
{
  //delete everything that you declared with new
  delete ShieldingRadiusCommand;
  delete ThermalFluxCalcDir;

}

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					SetNewValue()
//------++++++------++++++------++++++------++++++------++++++------++++++------
void ThermalFluxCalcMessenger::SetNewValue( G4UIcommand *command, G4String newValue )
{
  if( command == ShieldingRadiusCommand ) 
      ThermalFluxCalcdetector->SetShieldingRadius( G4UIcmdWithADoubleAndUnit::GetNewDoubleValue( newValue.data() )  );
}

