////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define TMS geometry
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

#ifndef TMS_TPC_HH
#define TMS_TPC_HH 1

//
//      GEANT4 includes
//
#include "globals.hh"

//
//      BACCARAT includes
//
#include "BaccDetector.hh"
#include "BaccManager.hh"

//
//	Project-specific includes
//
//#include "TMS_TPCParameters.hh"

//
//      Class forwarding
//
class G4LogicalVolume;
class BaccDetectorComponent;
class G4NistManager;
class BaccMaterials;
class TMSMessenger;
class TMSMaterials;

//------++++++------++++++------++++++------++++++------++++++------++++++------
class TMS_TPC
{
public:
  TMS_TPC();
  ~TMS_TPC();
  
  inline G4LogicalVolume *GetLogicalVolume() { return tpcVolume_log; }

  
private:
  TMSMaterials *TMSmaterials;
  BaccMaterials *BACCmaterials;

  G4LogicalVolume * tpcVolume_log;
 
};

#endif
