////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define TMS geometry
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

#ifndef TMSDetector_HH
#define TMSDetector_HH 1

//
//      GEANT4 includes
//
#include "globals.hh"

//
//      BACCARAT includes
//
#include "BaccDetector.hh"
#include "BaccManager.hh"

//
//	Project-specific includes
//
#include "TMSDetectorParameters.hh"

//
//      Class forwarding
//
class G4LogicalVolume;
class BaccDetectorComponent;
class G4NistManager;
class BaccMaterials;
class TMSMessenger;
class TMSMaterials;

//------++++++------++++++------++++++------++++++------++++++------++++++------
class TMSDetector : public BaccDetector
{
public:
  TMSDetector( G4String, G4String );
  ~TMSDetector();
  
  void BuildDetector();
  G4ThreeVector SetOrigin(BaccDetectorComponent *);
  void InitializeDetector();

  //  Registration methods below

  
private:
  TMSMessenger *TMSmessenger;
  TMSMaterials *TMSmaterials;
  G4NistManager *NISTmaterials;
  BaccMaterials *BACCmaterials;
  
};

#endif
