////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define TMS materials
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

#ifndef TMSMaterials_HH
#define TMSMaterials_HH 1

//
//	c++ includes
//
#include <map>

//
//	Geant4 includes
//
#include "G4String.hh"

//
//	Class forwarding
//
class G4Material;
class G4VisAttributes;
//class G4MaterialPropertiesTable;
class G4OpticalSurface;

typedef std::map<G4String, G4Material*> material_map;
//typedef std::map<G4String, G4MaterialPropertiesTable*> property_map;
typedef std::map<G4String, G4VisAttributes*> vis_map;
typedef std::map<G4String, G4OpticalSurface*> optical_map;

//------++++++------++++++------++++++------++++++------++++++------++++++------
class TMSMaterials
{
public:
  TMSMaterials();
  ~TMSMaterials();
  
  static TMSMaterials *GetInstance();
  
  G4Material *GetMaterialByName(G4String);
  G4VisAttributes *GetVisAttributesByName(G4String);
  //  G4MaterialPropertiesTable *GetPropertiesTableByName(G4String);
  G4OpticalSurface *GetOpticalSurfaceByName(G4String);
  
  inline G4Material* LiquidXe() { return liquidXe; }
  inline G4Material* TMS() { return tms; }
  inline G4Material* Paraffin() { return paraffin; }
  inline G4Material* BoratedWater() { return boratedWater; }
  inline G4Material* BoratedPE_HD() { return boratedPE_HD; }
  inline G4Material* BoratedPE_LD() { return boratedPE_LD; }
  inline G4Material* BoratedPE_WD() { return boratedPE_WD; }
  inline G4Material* SodiumIodide() { return sodiumIodide; }
  inline G4Material* EJ276() { return ej276; }
 
  inline G4VisAttributes* LiquidXeVis() { return liquidXeVis; }
  inline G4VisAttributes* TMSVis() { return tmsVis; } 
  inline G4VisAttributes* ParaffinVis() { return paraffinVis; }
  inline G4VisAttributes* BoratedWaterVis() { return boratedWaterVis; }


private:
  
  static TMSMaterials *TMSmaterials;
  
  material_map materials;
  //  property_map properties;
  vis_map visattributes;
  optical_map opticals;
  
  void CreateMaterials();
  void CreateOpticalSurfaces();
  void CreateVisualAttributes();

  G4Material* liquidXe;
  G4Material* tms;
  G4Material * boratedWater;
  G4Material * paraffin; 
  G4Material * boratedPE_HD;
  G4Material * boratedPE_LD;
  G4Material * boratedPE_WD;
  G4Material * sodiumIodide;
  G4Material * ej276;
 
  G4VisAttributes* liquidXeVis;
  G4VisAttributes* tmsVis;
  G4VisAttributes* boratedWaterVis;
  G4VisAttributes* paraffinVis;

};

#endif
