/run/verbose 1
/control/verbose 0
/grdm/verbose 0
/process/verbose 0
/tracking/verbose 1

/run/initialize
/Bacc/io/outputDir ./ 
#/p/lustre1/lenardo1/simulations/CrystalSims/20210619_StanfordDetectorSims/
/Bacc/io/outputName NaI_scintillator_StanfordCrystal_0010keV_
/Bacc/detector/select GammaEfficienciesDetector
/Bacc/detector/update

/Bacc/detector/recordLevel scintillator 2

/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre 0., 0., 0., cm
/gps/pos/halfz 0.635 cm
/gps/pos/radius 0.05 cm
/gps/pos/rot1 0 0 1
/gps/pos/rot2 0 1 0
/gps/particle gamma
/gps/ang/type iso
/gps/energy 10.0 keV

/Bacc/physicsList/useOpticalProcesses 0

/Bacc/beamOn 10
exit
