////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define the messenger
// commands for the GammaEfficiencies project.
// All geometry, physics, io managements, etc, happen here
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

//
//	GEANT4 includes
//
#include "G4UIdirectory.hh"
// uncomment the headers that you will need
//#include "G4UIcmdWithAnInteger.hh"
//#include "G4UIcmdWithoutParameter.hh"
//#include "G4UIcmdWithAString.hh"
//#include "G4UIcmdWithABool.hh"
//#include "G4UIcmdWith3VectorAndUnit.hh"
//#include "G4UIcmdWithADoubleAndUnit.hh"
//#include "G4UIcmdWith3Vector.hh"
//#include "G4UIcmdWithADouble.hh"
#include "globals.hh"

//
// Project-specific includes
//
#include "GammaEfficienciesMessenger.hh"
#include "GammaEfficienciesDetector.hh"

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					Messenger()
//------++++++------++++++------++++++------++++++------++++++------++++++------
GammaEfficienciesMessenger::GammaEfficienciesMessenger( GammaEfficienciesDetector *Det )
  : GammaEfficienciesdetector( Det )
{
  //  Set up the directory
  GammaEfficienciesDir = new G4UIdirectory( "/GammaEfficiencies/" );
  GammaEfficienciesDir->SetGuidance( "All GammaEfficiencies project commands are contained under /GammaEfficiencies/" );

}

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					~Messenger()
//------++++++------++++++------++++++------++++++------++++++------++++++------
GammaEfficienciesMessenger::~GammaEfficienciesMessenger()
{
  //delete everything that you declared with new
  delete GammaEfficienciesDir;

}

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					SetNewValue()
//------++++++------++++++------++++++------++++++------++++++------++++++------
void GammaEfficienciesMessenger::SetNewValue( G4UIcommand *command, G4String newValue )
{
  
}

