////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define the messenger
// commands for the GammaCounter project.
// All geometry, physics, io managements, etc, happen here
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

//
//	GEANT4 includes
//
#include "G4UIdirectory.hh"
// uncomment the headers that you will need
//#include "G4UIcmdWithAnInteger.hh"
//#include "G4UIcmdWithoutParameter.hh"
//#include "G4UIcmdWithAString.hh"
//#include "G4UIcmdWithABool.hh"
//#include "G4UIcmdWith3VectorAndUnit.hh"
#include "G4UIcmdWithADoubleAndUnit.hh"
//#include "G4UIcmdWith3Vector.hh"
//#include "G4UIcmdWithADouble.hh"
#include "globals.hh"

//
// Project-specific includes
//
#include "GammaCounterMessenger.hh"
#include "GammaCounterDetector.hh"

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					Messenger()
//------++++++------++++++------++++++------++++++------++++++------++++++------
GammaCounterMessenger::GammaCounterMessenger( GammaCounterDetector *Det )
  : GammaCounterdetector( Det )
{
  //  Set up the directory
  GammaCounterDir = new G4UIdirectory( "/GammaCounter/" );
  GammaCounterDir->SetGuidance( "All GammaCounter project commands are contained under /GammaCounter/" );
  
  ShieldingRadiusCommand = new G4UIcmdWithADoubleAndUnit( "/GammaCounter/shieldingRadius", this );
  ShieldingRadiusCommand->AvailableForStates( G4State_PreInit, G4State_Idle );

}

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					~Messenger()
//------++++++------++++++------++++++------++++++------++++++------++++++------
GammaCounterMessenger::~GammaCounterMessenger()
{
  //delete everything that you declared with new
  delete ShieldingRadiusCommand;
  delete GammaCounterDir;

}

//------++++++------++++++------++++++------++++++------++++++------++++++------
//					SetNewValue()
//------++++++------++++++------++++++------++++++------++++++------++++++------
void GammaCounterMessenger::SetNewValue( G4UIcommand *command, G4String newValue )
{
  if( command == ShieldingRadiusCommand ) 
      GammaCounterdetector->SetShieldingRadius( G4UIcmdWithADoubleAndUnit::GetNewDoubleValue( newValue.data() )  );
}

