####################################################################################################
# example macro for the LUXSim package                                                             #
#                                                                                                  #
# Change log:                                                                                      #
# 19 Aug 2013 - Initial submission (Vic)                                                           #
#                                                                                                  #
####################################################################################################
/run/verbose 1
/control/verbose 0
/tracking/verbose 0
/grdm/verbose 0
/process/verbose 0

# Set up visualization - Comment this stuff out if you want to skip visualization
#/vis/open OGLSQt 1200x1200-0+0
#/vis/open VRML2FILE
#/vis/drawVolume
#/vis/scene/add/trajectories
#/vis/scene/endOfEventAction accumulate
#/tracking/storeTrajectory 1
#/vis/viewer/set/viewpointVector 0.5 0.75 1
#/vis/viewer/set/upVector 0 0 1
#/vis/viewer/zoom 0 
#/vis/viewer/set/viewpointThetaPhi 45 45             
#/vis/viewer/set/style surface

# Set up visualization so that we don't cloud the issue with neutrinos - Comment this stuff out if you want to skip visualization
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add nu_e
#/vis/filtering/trajectories/particleFilter-0/add nu_mu
#/vis/filtering/trajectories/particleFilter-0/add nu_tau
#/vis/filtering/trajectories/particleFilter-0/add anti_nu_e
#/vis/filtering/trajectories/particleFilter-0/add anti_nu_mu
#/vis/filtering/trajectories/particleFilter-0/add anti_nu_tau
#/vis/filtering/trajectories/particleFilter-0/invert true

# Color keys: white, gray, grey, black, red, green, blue, cyan, magenta, yellow - Comment this stuff out if you want to skip visualization
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
#/vis/modeling/trajectories/drawByParticleID-0/set e- magenta
#/vis/modeling/trajectories/drawByParticleID-0/set proton cyan
#/vis/modeling/trajectories/drawByParticleID-0/set neutron grey
#/vis/modeling/trajectories/drawByParticleID-0/set gamma green
#/vis/modeling/trajectories/drawByParticleID-0/set opticalPhoton yellow

# This next set of lines is to, as it appears, initialize the simulation
/run/initialize

# Set the output directory
/Bacc/io/outputDir /usr/workspace/wsb/lenardo1/simulations/
/Bacc/io/outputName TMS_4MeVNeutrons_Conical_CylindricalSource_
/Bacc/io/updateFrequency 100000


# Set the random seed
#/Bacc/randomSeed 0

# Select the kind of detector to use
#/Bacc/detector/select simpleExample
#/Bacc/detector/select complexExample
#/Bacc/detector/select LLNLSinglePhase
/Bacc/detector/select TMSDetector
#/XeNeu/ddShieldingOn true

# Update geometry
/Bacc/detector/update

# Set the record level for one of the volumes to write some information about it
#/Bacc/detector/recordLevel LiquidXeTarget 2 # For "simpleExample" or "complexExample"
#/Bacc/detector/recordLevel activeVolume 2 # For "LLNLSinglePhase"
/Bacc/detector/recordLevel tms_volume 2 # For "GNARRLIDetector"
/Bacc/detector/recordLevel top_flange 2 
/Bacc/detector/recordLevel bottom_flange 2 
/Bacc/detector/recordLevel top_nipple_flange 2 
/Bacc/detector/recordLevel bottom_nipple_flange 2 
/Bacc/detector/recordLevel active_tms_volume 2
/Bacc/detector/recordLevel tms_volume 2
/Bacc/detector/recordLevel cathode 2
/Bacc/detector/recordLevel small_flange 2 
/Bacc/detector/recordLevel detector_can 2 
/Bacc/detector/recordLevel bolt 2
/Bacc/detector/recordLevel psd_target 2
/Bacc/detector/recordLevel lead 2
/Bacc/detector/recordLevel collimator 2

/gps/particle neutron
/gps/energy 4. MeV
/gps/ene/type Gauss
/gps/ene/sigma 0.05 MeV
/gps/position 0 0 0 m
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/radius 1.2 cm
/gps/pos/halfz 2.54 cm
/gps/ang/type iso
#/gps/hist/type theta
/gps/ang/mintheta 0. deg
/gps/ang/maxtheta 15. deg
#/gps/ang/minphi 160. deg
#/gps/ang/maxphi 200. deg
/gps/ang/rot1 0 0 -1
/gps/ang/rot2 0 -1 0


/Bacc/physicsList/useOpticalProcesses 0

/Bacc/beamOn 1000000

exit
