////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define the messenger
// commands for the ThermalFluxCalc project.
// All geometry, physics, io managements, etc, happen here
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

#ifndef ThermalFluxCalcMessenger_HH
#define ThermalFluxCalcMessenger_HH 1

//
//      GEANT4 includes
//
#include "globals.hh"
#include "G4UImessenger.hh"

//
//      Class forwarding
//
class G4UIdirectory;
// Uncomment the class that you will need
//class G4UicmdWithAnInteger;
//class G4UicmdWithoutParameter;
//class G4UicmdWithAString;
//class G4UicmdWithABool;
class G4UIcmdWithADoubleAndUnit;
//class G4UicmdWithADouble;

class ThermalFluxCalcDetector;

//------++++++------++++++------++++++------++++++------++++++------++++++------
class ThermalFluxCalcMessenger : public G4UImessenger
{
public:
  ThermalFluxCalcMessenger( ThermalFluxCalcDetector* );
  ~ThermalFluxCalcMessenger();
  
  void SetNewValue( G4UIcommand*, G4String );
  
private:
  ThermalFluxCalcDetector *ThermalFluxCalcdetector;
  
  //      The directory
  G4UIdirectory *ThermalFluxCalcDir;

  // Declare the UI commands below
  G4UIcmdWithADoubleAndUnit * ShieldingRadiusCommand;

  
};

#endif
