////////////////////////////////////////////////////////////////////////////////
//
// This code is automatically generated by BACCARAT to define ThermalFluxCalc parameters
//
////////////////////////////////////////////////////////////////////////////////
//
//      Change log
// 17 March 2016 - Initial Template submission (Jingke)
//
////////////////////////////////////////////////////////////////////////////////

#ifndef ThermalFluxCalcDetectorParameters_h
#define ThermalFluxCalcDetectorParameters_h 1

#include "G4SystemOfUnits.hh"

namespace ThermalFluxCalcDetectorParameters{
  
  //define your detector parameters here
  
}

#endif
